Repository 567-labs/instructor, pull requests merged in 2024-04, with the labels that each got.

#561 Add from_groq support #556
  docs/examples/groq.md
  docs/examples/index.md
  examples/groq/groq_example.py
  examples/groq/groq_example2.py
  instructor/__init__.py
  instructor/client.py
  tests/llm/test_openai/test_validators.py
Labels: documentation, enhancement, size:L

#562 refactor(instructor): improve client handling and code modularity
  instructor/__init__.py
  instructor/client.py
  instructor/client_anthropic.py
  instructor/client_groq.py
Labels: enhancement, size:L

#560 feat: fix anthropic reasking
  examples/groq/groq_example2.py
  instructor/__init__.py
  instructor/client_anthropic.py
  instructor/function_calls.py
  instructor/process_response.py
  instructor/retry.py
  instructor/utils.py
  tests/llm/test_anthropic/evals/test_simple.py
  tests/test_utils.py
Labels: enhancement, size:L

#563 feat: Partial jiter
  examples/partial_streaming/benchmark.py
  examples/partial_streaming/run.py
  instructor/dsl/partial.py
  instructor/dsl/partialjson.py
  poetry.lock
  pyproject.toml
Labels: enhancement, size:L

#565 Allow extras dependencies to truly be optional
  poetry.lock
  pyproject.toml
Labels: bug, enhancement, size:S

#569 feat: support anthropic tools
  README.md
  docs/concepts/caching.md
  docs/concepts/parallel.md
  docs/concepts/partial.md
  docs/concepts/raw_response.md
  docs/concepts/reask_validation.md
  docs/concepts/retrying.md
  docs/concepts/types.md
  docs/hub/anthropic.md
  docs/hub/pandas_df.md
  docs/index.md
  examples/partial_streaming/run.py
  instructor/anthropic_utils.py
  instructor/client_anthropic.py
  instructor/dsl/partial.py
  instructor/function_calls.py
  instructor/process_response.py
  instructor/retry.py
  instructor/test.py
  poetry.lock
  pyproject.toml
  tests/llm/test_anthropic/evals/test_simple.py
Labels: enhancement, size:L

#570 docs: use `async for` instead of `for` for streaming FastAPI resp
  docs/concepts/fastapi.md
Labels: bug, documentation, size:XS

#572 docs: fixes few typos in validation-part1
  docs/blog/posts/validation-part1.md
Labels: documentation, size:S

#577 fix broken link to evals
  docs/contributing.md
Labels: bug, documentation, size:XS

#573 docs: fix typo in bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, size:XS

#586 deps(typer): adjust dependency range
  poetry.lock
  pyproject.toml
Labels: enhancement, size:XS, lgtm

#583 Update retry.py
  instructor/retry.py
Labels: bug, size:XS

#579 Refactor anthropic message format to support tool messages & Allows Anthropic Bedrock clients
  instructor/client_anthropic.py
  instructor/retry.py
  instructor/utils.py
  tests/test_new_client.py
  tests/test_utils.py
Labels: enhancement, size:L, lgtm

#590 fix typo textblocks vi-fr
  examples/match_language/run_v1.py
  examples/match_language/run_v2.py
Labels: bug, size:XS

#585 Add support for cohere models
  README.md
  docs/examples/document_segmentation.md
  docs/examples/index.md
  docs/hub/cohere.md
  examples/cohere/cohere.py
  examples/extract-table/run_vision.py
  examples/extract-table/test.py
  instructor/__init__.py
  instructor/client_cohere.py
  instructor/function_calls.py
  instructor/mode.py
  instructor/process_response.py
  instructor/retry.py
  instructor/utils.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/test_new_client.py
Labels: enhancement, size:XL

#595 adding AnthropicVertex
  instructor/client_anthropic.py
Labels: enhancement, size:S

#596 fix: typo textblocks vi-fr in blog post
  docs/blog/posts/matching-language.md
Labels: bug, documentation, size:XS

#597 Document use of SkipJsonSchema for omitting fields
  docs/concepts/fields.md
  docs/concepts/models.md
Labels: documentation, size:S

#601 Support python 3.9
  .github/workflows/test.yml
  examples/cohere/cohere.py
  examples/extract-table/run_vision_org_table.py
  examples/fizzbuzz/run.py
  examples/parallel/run.py
  instructor/client.py
  instructor/client_anthropic.py
  instructor/client_cohere.py
  instructor/client_groq.py
  instructor/dsl/parallel.py
  instructor/dsl/partial.py
  instructor/patch.py
  instructor/process_response.py
  instructor/retry.py
  instructor/utils.py
  poetry.lock
  pyproject.toml
  tests/llm/test_openai/test_parallel.py
  tests/test_new_client.py
Labels: bug, enhancement, size:M

#610 feat: basic sentiment analysis eval tests
  tests/llm/test_openai/evals/test_sentiment_analysis.py
Labels: enhancement, size:M

#599 From mistral
  docs/examples/mistral.md
  examples/mistral/mistral.py
  instructor/__init__.py
  instructor/client_mistral.py
  instructor/utils.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
  tests/test_new_client.py
Labels: documentation, enhancement, size:L, lgtm

#614 feat: custome exceptions
  docs/concepts/fields.md
  docs/concepts/retrying.md
  instructor/cli/usage.py
  instructor/client.py
  instructor/client_anthropic.py
  instructor/client_cohere.py
  instructor/client_groq.py
  instructor/patch.py
  instructor/retry.py
  pyproject.toml
Labels: enhancement, size:L

#621 Fix bullet list in README.md
  README.md
Labels: documentation, size:XS

#625 Update README.md
  README.md
Labels: documentation, size:XS

#626 fix typo about Enum 'and' → 'an'
  docs/concepts/enums.md
  docs/concepts/prompting.md
Labels: documentation, size:XS

#622 Fix anthropic usage and tools
  instructor/function_calls.py
  instructor/retry.py
  instructor/utils.py
  tests/llm/test_anthropic/evals/test_simple.py
Labels: bug, enhancement, size:L, lgtm

#618 feat: update and allow strict mode
  instructor/client.py
  instructor/patch.py
Labels: enhancement, size:S

#620 feat: add watsonx support
  docs/examples/watsonx.md
  examples/watsonx/watsonx.py
  poetry.lock
  pyproject.toml
Labels: enhancement, size:L
