Repository 567-labs/instructor, pull requests merged in 2024-11, with the labels that each got.

#1162 feat: Adding new blog post
  docs/blog/posts/google-openai-client.md
Labels: documentation, enhancement, size:L

#1163 feat: Add Gemini PDF example
  docs/blog/posts/chat-with-your-pdf-with-gemini.md
Labels: documentation, enhancement

#1173 fix: fixed up tenacity link
  docs/blog/posts/chat-with-your-pdf-with-gemini.md
Labels: documentation, size:S

#1179 fix: removed use_async flag in cerebras client
  instructor/client_cerebras.py
Labels: bug, enhancement, size:M

#1180 fix: bump jiter dep
  instructor/batch.py
  instructor/dsl/citation.py
  instructor/dsl/iterable.py
  instructor/dsl/maybe.py
  instructor/dsl/validators.py
  instructor/multimodal.py
  poetry.lock
  pyproject.toml
Labels: size:S, dependencies

#1186 feat: adding new article on gemini citations
  docs/blog/posts/generating-pdf-citations.md
  docs/blog/posts/img/gemini_citations.png
Labels: documentation, enhancement, size:L

#1196 fix: remove table
  docs/integrations/index.md
Labels: documentation, size:S

#1204 Adding new tidy table article
  docs/blog/posts/google-openai-client.md
  docs/blog/posts/img/untidy_table.png
  docs/blog/posts/introducing-structured-outputs-with-cerebras-inference.md
  docs/blog/posts/llm-as-reranker.md
  docs/blog/posts/multimodal-gemini.md
  docs/blog/posts/openai-multimodal.md
  docs/blog/posts/pairwise-llm-judge.md
  docs/blog/posts/parea.md
  docs/blog/posts/rag-timelines.md
  docs/blog/posts/situate-context.md
  docs/blog/posts/structured-output-anthropic.md
  docs/blog/posts/tidy-data-from-messy-tables.md
  docs/blog/posts/using_json.md
Labels: documentation, enhancement, size:L

#1210 docs: update installation and usage examples for LLM integrations
  docs/index.md
Labels: documentation, enhancement, size:M

#1215 fix: adding type ignore for pyright
  instructor/dsl/partial.py
Labels: enhancement, size:L

#1214 feat: added deepseek page
  docs/integrations/deepseek.md
  mkdocs.yml
Labels: documentation, enhancement, size:M

#1225 feat: added cortex documentation
  docs/integrations/cortex.md
  docs/integrations/index.md
  mkdocs.yml
Labels: documentation, enhancement, size:L
