Repository 567-labs/instructor, pull requests merged in 2025-06, with the labels that each got.

#1575 Add Claude Code GitHub Workflow
  .github/workflows/claude.yml
Labels: documentation, enhancement, anthropic, size:M

#1577 feat: update README to reflect 3M monthly downloads milestone
  README.md
Labels: documentation, enhancement, size:S

#1602 feat(auto_client): add Ollama provider support
  docs/integrations/index.md
  docs/integrations/ollama.md
  instructor/auto_client.py
Labels: documentation, enhancement, size:M, python

#1603 fix: respect timeout parameter in retry mechanism for Ollama compatibility
  docs/concepts/retrying.md
  docs/integrations/ollama.md
  instructor/retry.py
Labels: bug, enhancement, size:M, python

#1604 fix(reask): handle ThinkingBlock in reask_anthropic_json
  instructor/reask.py
Labels: bug, size:M, python

#1606 docs: improve clarity and consistency across documentation
  README.md
  docs/concepts/philosophy.md
  docs/why.md
Labels: documentation, enhancement, size:M

#1625 fix(deps): relax tenacity requirement to support google-genai 1.21.1
  pyproject.toml
  uv.lock
Labels: size:M, dependencies, python

#1620 feat(docs): improve SEO for asyncio and tenacity documentation
  docs/blog/posts/learn-async.md
  docs/concepts/retrying.md
  docs/integrations/anthropic.md
  docs/integrations/google.md
  docs/integrations/index.md
  examples/asyncio-benchmarks/run.py
  examples/tenacity-benchmarks/run.py
  instructor/multimodal.py
  mkdocs.yml
  scripts/make_sitemap.py
  sitemap.yaml
Labels: documentation, enhancement, size:M, python

#1618 Feat/add gemini optional support
  .github/workflows/test.yml
  instructor/process_response.py
  instructor/utils.py
  tests/llm/test_genai/test_invalid_schema.py
  tests/llm/test_genai/test_schema_conversion.py
  tests/llm/test_openai/test_responses_tools.py
Labels: enhancement, size:M, python
