Repository 567-labs/instructor, pull requests merged in 2025-04, with the labels that each got.

#1462 feat: support PDFs for Genai SDK
  docs/integrations/genai.md
  instructor/multimodal.py
  instructor/utils.py
  tests/llm/test_genai/test_multimodal.py
Labels: documentation, enhancement, size:M, python

#1461 Adding support for Anthropic PDF
  docs/integrations/anthropic.md
  docs/integrations/genai.md
  instructor/multimodal.py
  instructor/utils.py
  tests/llm/test_anthropic/test_multimodal.py
  tests/llm/test_genai/test_multimodal.py
Labels: documentation, enhancement, anthropic, size:M, python

#1460 Feat/add openai pdf
  docs/concepts/multimodal.md
  docs/integrations/anthropic.md
  docs/integrations/genai.md
  docs/integrations/openai.md
  instructor/multimodal.py
  instructor/utils.py
  tests/llm/test_anthropic/test_multimodal.py
  tests/llm/test_genai/test_multimodal.py
  tests/llm/test_openai/test_multimodal.py
Labels: documentation, enhancement, size:L, python

#1459 feat: add mistral PDF support
  docs/concepts/multimodal.md
  docs/integrations/anthropic.md
  docs/integrations/genai.md
  docs/integrations/mistral.md
  docs/integrations/openai.md
  instructor/multimodal.py
  instructor/utils.py
  tests/llm/test_anthropic/test_multimodal.py
  tests/llm/test_genai/test_multimodal.py
  tests/llm/test_mistral/test_multimodal.py
  tests/llm/test_openai/test_multimodal.py
Labels: documentation, enhancement, size:L, python

#1479 Simplify learning docs for new users
  docs/index.md
  docs/learning/getting_started/client_setup.md
  docs/learning/getting_started/first_extraction.md
  docs/learning/getting_started/installation.md
  docs/learning/getting_started/response_models.md
  docs/learning/getting_started/structured_outputs.md
  docs/learning/index.md
  docs/learning/patterns/field_validation.md
  docs/learning/patterns/list_extraction.md
  docs/learning/patterns/nested_structure.md
  docs/learning/patterns/optional_fields.md
  docs/learning/patterns/prompt_templates.md
  docs/learning/patterns/simple_object.md
  docs/learning/streaming/basics.md
  docs/learning/streaming/lists.md
  docs/learning/validation/basics.md
  docs/learning/validation/custom_validators.md
  docs/learning/validation/field_level_validation.md
  docs/learning/validation/retry_mechanisms.md
  mkdocs.yml
Labels: documentation, enhancement, size:M

#1505 Fix: simple test failure
  instructor/dsl/simple_type.py
  tests/dsl/test_simple_type_fix.py
  tests/test_fizzbuzz_fix.py
Labels: bug, size:S, python
