Repository 567-labs/instructor, pull requests merged in 2025-05, with the labels that each got.

#1506 Added a check for genai response
  instructor/reask.py
Labels: bug, enhancement, size:M, python

#1504 Add custom error message for Gemini Optional and Enums
  docs/integrations/genai.md
  instructor/process_response.py
  instructor/utils.py
  tests/llm/test_genai/test_invalid_schema.py
Labels: documentation, enhancement, size:M, python

#1513 Added provider names
  .github/workflows/test.yml
  instructor/auto_client.py
  instructor/models.py
Labels: documentation, enhancement, size:L, python

#1515 docs(blog): add Anthropic web search structured data blog post
  docs/blog/posts/anthropic-web-search-structured.md
  examples/anthropic-web-tool/run.py
  instructor/function_calls.py
Labels: documentation, enhancement, size:M

#1517 Fix/mkdocs
  docs/blog/posts/anthropic-web-search-structured.md
  requirements.txt
Labels: documentation, dependencies

#1516 docs(blog): announce unified provider interface (from_provider)
  docs/blog/index.md
  docs/blog/posts/announcing-unified-provider-interface.md
  docs/blog/posts/img/instructor-autocomplete.png
Labels: documentation, enhancement, size:M

#1519 Fix/anthropic web search
  docs/blog/posts/anthropic-web-search-structured.md
  examples/anthropic-web-tool/run.py
  instructor/function_calls.py
Labels: documentation, enhancement, anthropic, size:M, python

#1524 fix: removed print statement
  instructor/utils.py
  pyproject.toml
Labels: size:XS, dependencies, python

#1520 Implementing support for responses
  .github/workflows/test.yml
  docs/blog/posts/announcing-instructor-responses-support.md
  docs/integrations/index.md
  docs/integrations/openai-responses.md
  instructor/client.py
  instructor/dsl/iterable.py
  instructor/dsl/partial.py
  instructor/function_calls.py
  instructor/mode.py
  instructor/multimodal.py
  instructor/process_response.py
  instructor/reask.py
  pyproject.toml
  tests/llm/test_openai/evals/test_entities.py
  tests/llm/test_openai/evals/test_extract_users.py
  tests/llm/test_openai/evals/test_sentiment_analysis.py
  tests/llm/test_openai/test_modes.py
  tests/llm/test_openai/test_multimodal.py
  tests/llm/test_openai/test_multitask.py
  tests/llm/test_openai/test_patch.py
  tests/llm/test_openai/test_response.py
  tests/llm/test_openai/test_responses_tools.py
  tests/llm/test_openai/test_retries.py
  tests/llm/test_openai/test_stream.py
  tests/llm/test_openai/test_validation_context.py
  tests/llm/test_openai/util.py
  tests/test_multimodal.py
Labels: enhancement, size:M, python

#1544 fix: remove failing test
  tests/llm/test_openai/test_responses_tools.py
  tests/test_auto_client.py
Labels: bug, size:S, python

#1549 feat: Improve error handling with comprehensive exception hierarchy
  docs/concepts/error_handling.md
  docs/concepts/hooks.md
  docs/concepts/retrying.md
  instructor/auto_client.py
  instructor/client_anthropic.py
  instructor/client_bedrock.py
  instructor/client_cerebras.py
  instructor/client_cohere.py
  instructor/client_fireworks.py
  instructor/client_gemini.py
  instructor/client_genai.py
  instructor/client_groq.py
  instructor/client_mistral.py
  instructor/client_perplexity.py
  instructor/client_vertexai.py
  instructor/client_writer.py
  instructor/exceptions.py
  instructor/function_calls.py
  instructor/patch.py
  instructor/process_response.py
  instructor/retry.py
  mkdocs.yml
  tests/test_auto_client.py
Labels: documentation, enhancement, size:L, python

#1562 Remove `enable_prompt_caching` from Anthropic integration since we ha…
  docs/integrations/anthropic.md
  instructor/client_anthropic.py
Labels: documentation, anthropic, size:L, python

#1561 Fix/docs
  docs/blog/index.md
  docs/blog/posts/announcing-instructor-responses-support.md
  docs/blog/posts/announcing-unified-provider-interface.md
  docs/concepts/semantic_validation.md
  docs/examples/classification.md
  docs/examples/index.md
  docs/examples/tracing_with_langfuse.md
  docs/learning/patterns/field_validation.md
  docs/learning/patterns/list_extraction.md
  docs/learning/patterns/nested_structure.md
  docs/learning/patterns/optional_fields.md
  docs/learning/patterns/prompt_templates.md
  docs/learning/streaming/lists.md
  docs/learning/validation/custom_validators.md
  docs/learning/validation/field_level_validation.md
  docs/learning/validation/retry_mechanisms.md
  instructor/dsl/validators.py
  instructor/function_calls.py
  mkdocs.yml
Labels: documentation, size:M
