Repository 567-labs/instructor, pull requests merged in 2025-03, with the labels that each got.

#1378 Optimize dictionary operations in retry, reask, and utils modules
  docs/concepts/dictionary_operations.md
  instructor/reask.py
  instructor/retry.py
  instructor/utils.py
  mkdocs.yml
  tests/test_dict_operations.py
  tests/test_dict_operations_validation.py
Labels: documentation, enhancement, size:M

#1375 feat: optimize message processing
  .pre-commit-config.yaml
  docs/concepts/dictionary_operations.md
  instructor/reask.py
  instructor/retry.py
  instructor/utils.py
  mkdocs.yml
  tests/test_dict_operations.py
  tests/test_dict_operations_validation.py
  tests/test_json_extraction.py
  tests/test_message_processing.py
Labels: enhancement, size:M

#1374 feat: optimize JSON extraction and parsing
  .pre-commit-config.yaml
  docs/concepts/dictionary_operations.md
  instructor/function_calls.py
  instructor/reask.py
  instructor/retry.py
  instructor/utils.py
  mkdocs.yml
  tests/test_dict_operations.py
  tests/test_dict_operations_validation.py
  tests/test_json_extraction.py
  tests/test_json_extraction_edge_cases.py
  tests/test_message_processing.py
Labels: enhancement, size:L

#1373 feat: optimizations
  .pre-commit-config.yaml
  docs/concepts/caching.md
  docs/concepts/dictionary_operations.md
  docs/concepts/hooks.md
  docs/concepts/iterable.md
  docs/concepts/lists.md
  docs/concepts/maybe.md
  docs/concepts/multimodal.md
  docs/concepts/parallel.md
  docs/concepts/partial.md
  docs/concepts/prompt_caching.md
  docs/concepts/raw_response.md
  docs/concepts/retrying.md
  docs/concepts/templating.md
  docs/concepts/types.md
  docs/concepts/unions.md
  docs/concepts/usage.md
  docs/concepts/validation.md
  examples/hooks/README.md
  examples/hooks/run.py
  instructor/client.py
  instructor/function_calls.py
  instructor/hooks.py
  instructor/mode.py
  instructor/reask.py
  instructor/retry.py
  instructor/utils.py
  mkdocs.yml
  tests/test_dict_operations.py
  tests/test_dict_operations_validation.py
  tests/test_function_calls.py
  tests/test_json_extraction.py
  tests/test_json_extraction_edge_cases.py
  tests/test_message_processing.py
Labels: documentation, enhancement, size:M

#1388 fix: update links to point to our repo files
  .github/workflows/test.yml
  .github/workflows/test_docs.yml
  tests/llm/test_openai/test_multimodal.py
  tests/llm/test_perplexity/test_modes.py
Labels: size:S, python

#1386 feat: Adding support for Open Router
  docs/integrations/index.md
  docs/integrations/openrouter.md
  instructor/client.py
  instructor/function_calls.py
  instructor/mode.py
  instructor/process_response.py
  instructor/utils.py
  mkdocs.yml
Labels: documentation, enhancement, experimental, size:M, python

#1396 Updating docs and bumping Anthropic version
  docs/integrations/anthropic.md
  pyproject.toml
  uv.lock
Labels: documentation, size:M, dependencies, python

#1399 docs: improve documentation structure with visual diagrams
  docs/concepts/index.md
  docs/concepts/validation.md
  docs/prompting/index.md
  docs/start-here.md
  mkdocs.yml
Labels: documentation, enhancement, size:M

#1394 Jinja Templating and Documentation
  docs/integrations/genai.md
  docs/integrations/index.md
  instructor/patch.py
  instructor/templating.py
  tests/llm/test_genai/test_format.py
  tests/test_formatting.py
Labels: documentation, enhancement, size:M, python

#1391 Adding Structured Outputs for Mistral
  .github/workflows/test.yml
  docs/integrations/mistral.md
  instructor/client_mistral.py
  instructor/function_calls.py
  instructor/mode.py
  instructor/process_response.py
  instructor/reask.py
  pyproject.toml
  tests/llm/test_mistral/__init__.py
  tests/llm/test_mistral/conftest.py
  tests/llm/test_mistral/test_modes.py
  tests/llm/test_mistral/test_retries.py
  tests/llm/test_mistral/util.py
  uv.lock
Labels: documentation, enhancement, size:L, dependencies, python

#1409 Implementing Retries with the GenAI Sdk
  .github/workflows/test.yml
  docs/integrations/genai.md
  instructor/function_calls.py
  instructor/multimodal.py
  instructor/reask.py
  mkdocs.yml
  tests/llm/test_genai/test_format.py
  tests/llm/test_genai/test_retries.py
  tests/llm/test_genai/test_stream.py
Labels: enhancement, size:M, python

#1408 Add Streaming Support for GenAI
  .github/workflows/ruff.yml
  .github/workflows/test.yml
  docs/integrations/genai.md
  instructor/client_genai.py
  instructor/dsl/partial.py
  instructor/function_calls.py
  instructor/multimodal.py
  instructor/reask.py
  mkdocs.yml
  tests/llm/test_genai/test_format.py
  tests/llm/test_genai/test_retries.py
  tests/llm/test_genai/test_stream.py
Labels: enhancement, size:M, python

#1404 Add genai image supp
  .github/workflows/ruff.yml
  .github/workflows/test.yml
  docs/integrations/genai.md
  instructor/client_genai.py
  instructor/dsl/partial.py
  instructor/function_calls.py
  instructor/multimodal.py
  instructor/process_response.py
  instructor/reask.py
  instructor/utils.py
  mkdocs.yml
  tests/llm/test_genai/test_format.py
  tests/llm/test_genai/test_multimodal.py
  tests/llm/test_genai/test_retries.py
  tests/llm/test_genai/test_stream.py
  tests/llm/test_openai/test_multimodal.py
Labels: enhancement, size:M, python

#1393 Adding support for the GenAI Sdk
  .github/workflows/ruff.yml
  .github/workflows/test.yml
  docs/integrations/genai.md
  docs/integrations/index.md
  instructor/__init__.py
  instructor/client_genai.py
  instructor/dsl/partial.py
  instructor/function_calls.py
  instructor/mode.py
  instructor/multimodal.py
  instructor/patch.py
  instructor/process_response.py
  instructor/reask.py
  instructor/templating.py
  instructor/utils.py
  mkdocs.yml
  pyproject.toml
  tests/llm/test_genai/__init__.py
  tests/llm/test_genai/conftest.py
  tests/llm/test_genai/test_format.py
  tests/llm/test_genai/test_multimodal.py
  tests/llm/test_genai/test_retries.py
  tests/llm/test_genai/test_simple.py
  tests/llm/test_genai/test_stream.py
  tests/llm/test_genai/util.py
  tests/llm/test_openai/test_multimodal.py
  tests/test_formatting.py
  uv.lock
Labels: enhancement, size:M, dependencies, python

#1411 Update UV reps
  pyproject.toml
  uv.lock
Labels: size:M, dependencies, python

#1414 fix: fixing incorrect import issue
  instructor/__init__.py
Labels: bug, size:S, python

#1417 fix: bump version + fix deps
  instructor/__init__.py
  pyproject.toml
Labels: size:S, dependencies, python

#1423 docs: Add Cursor rules documentation
  .cursor/rules/documentation-sync.mdc
  .cursor/rules/followups.mdc
  .cursor/rules/new-features-planning.mdc
  .cursor/rules/readme.md
  .cursor/rules/simple-language.mdc
Labels: documentation

#1424 docs: improve contributing guidelines with UV installation and conventional comments
  CONTRIBUTING.md
  docs/contributing.md
Labels: documentation, enhancement, size:L

#1427 docs(github): update cursor rules with proper website link and multiline PR instructions
  .cursor/rules/new-features-planning.mdc
Labels: documentation, enhancement, size:M

#1428 docs(streaming): improve documentation and code quality for Mistral and VertexAI streaming
  .cursor/rules/documentation-sync.mdc
  .cursor/rules/followups.mdc
  .cursor/rules/new-features-planning.mdc
  .cursor/rules/readme.md
  .cursor/rules/simple-language.mdc
  CONTRIBUTING.md
  docs/contributing.md
  docs/integrations/mistral.md
  docs/integrations/vertex.md
  docs/llm.txt
  docs/modes-comparison.md
  instructor/client_mistral.py
  instructor/dsl/iterable.py
  instructor/dsl/partial.py
  mkdocs.yml
Labels: documentation, enhancement, size:L, python

#1420 Adding Streaming for Mistral and VertexAI
  docs/integrations/mistral.md
  docs/integrations/vertex.md
  docs/modes-comparison.md
  instructor/client_mistral.py
  instructor/dsl/iterable.py
  instructor/dsl/partial.py
  tests/llm/test_mistral/test_stream.py
  tests/llm/test_vertexai/test_stream.py
  tests/llm/test_vertexai/util.py
  uv.lock
Labels: enhancement, size:M, dependencies, python

#1430 docs(blog): add post about Cursor rules for Git best practices
  docs/blog/posts/cursor-rules.md
Labels: documentation

#1431 docs(blog): announce llms.txt implementation
  docs/blog/index.md
  docs/blog/posts/llms-txt-adoption.md
Labels: documentation, enhancement

#1433 docs: add OpenAI audio extraction example
  docs/examples/audio_extraction.md
  mkdocs.yml
Labels: documentation, size:M

#1446 feat: added new article
  docs/blog/posts/img/agent_mcp_example.png
  docs/blog/posts/img/claude_desktop_mcp.png
  docs/blog/posts/img/claude_desktop_screenshot.png
  docs/blog/posts/img/cursor_mcp_agent.png
  docs/blog/posts/img/cursor_mcp_support.png
  docs/blog/posts/img/mcp_architecture.png
  docs/blog/posts/img/mcp_stars.webp
  docs/blog/posts/why-care-about-mcps.md
Labels: documentation, enhancement, size:L, python
